### ISSUE TITLE
New shards coming - Old shards removed

### ISSUE THREAD

**Issue by asad-awadia** [urakozz/go-dynamodb-stream-subscriber#5]
Does this library deal with the shards mutating? New shards coming in? Old shards getting removed etc? rebalancing etc? @urakozz

**Comment by urakozz** [comment]
It used to 3 years ago. Check the code, there is just 1 file there :) 
https://github.com/urakozz/go-dynamodb-stream-subscriber/blob/master/stream/stream.go#L174
https://github.com/urakozz/go-dynamodb-stream-subscriber/blob/master/stream/stream.go#L235
